version: '3'
services:
  redis-server:
    image: redis:6.0
    volumes:
      - ${ESPY_CONFIG_DIR:-/etc/espy}:/etc/espy
    sysctls:
      net.core.somaxconn: 512
      net.ipv4.tcp_max_syn_backlog: 512
    ports:
      - "${ESPY_REDIS_PORT:-6379}:6379"
    command: ["redis-server", "/etc/espy/redis.conf"]

  espy:
    image: quay.io/activecm/espy:${VERSION:-latest}
    build: .
    volumes:
        - ${ESPY_CONFIG_DIR:-/etc/espy}:/etc/espy
        - ${ESPY_ZEEK_LOGS:-/opt/zeek/logs}:/opt/zeek/logs

#  redis-cli:
#    image: redis:6.0
#    volumes:
#      - ${ESPY_CONFIG_DIR:-/etc/espy}:/etc/espy
#    command: ["redis-cli", "-h", "redis-server"]
