version: '3'
services:
  redis-server:
    image: redis:6.0
    volumes:
      - ${ESPY_CONFIG_DIR:-/etc/Espy}:/etc/Espy
    sysctls:
      net.core.somaxconn: 512
      net.ipv4.tcp_max_syn_backlog: 512
    ports:
      - "${ESPY_REDIS_PORT:-6379}:6379"
    command: ["redis-server", "/etc/Espy/redis.conf"]

  redis-cli:
    image: redis:6.0
    volumes:
      - ${ESPY_CONFIG_DIR:-/etc/Espy}:/etc/Espy
    command: ["redis-cli", "-h", "redis-server"]