winlogbeat.event_logs:
  - name: Microsoft-Windows-Sysmon/Operational
    event_id: 3
    processors:
      - script:
          lang: javascript
          id: sysmon
          file: ${path.home}/module/sysmon/config/winlogbeat-sysmon.js

# TODO: TLS
output.redis:
  # I was using a Windows VM with a briged adapter and connecting to my dev machine via the local network
  hosts: ["192.168.1.157"]
  key: "net-data:sysmon"
  password: "NET_AGENT_SECRET_PLACEHOLDER"

